### ISSUE TITLE
Tests fail due to kappa-osm errors

### ISSUE THREAD

**Issue by arky** [digidem/osm-p2p-geojson#17]
Running 'tape test' fails on both local gnu/linux machine and Travis-CI with following error: 

`> osm-p2p-geojson@4.0.2 test /home/travis/build/arky/osm-p2p-geojson
> tape 'test/**/*.js'

TAP version 13
# node
/home/travis/build/arky/osm-p2p-geojson/node_modules/kappa-osm/index.js:36
  this.core.writer('default', function (err, writer) {
            ^

TypeError: this.core.writer is not a function
    at new Osm (/home/travis/build/arky/osm-p2p-geojson/node_modules/kappa-osm/index.js:36:13)
    at Osm (/home/travis/build/arky/osm-p2p-geojson/node_modules/kappa-osm/index.js:21:38)
    at Object.createDb (/home/travis/build/arky/osm-p2p-geojson/test/utils.js:17:10)
    at osmDataToGeoJson (/home/travis/build/arky/osm-p2p-geojson/test/osmdata-to-geojson.js:15:13)
    at Test.<anonymous> (/home/travis/build/arky/osm-p2p-geojson/test/basic.js:10:3)
    at Test.bound [as _cb] (/home/travis/build/arky/osm-p2p-geojson/node_modules/tape/lib/test.js:77:32)
    at Test.run (/home/travis/build/arky/osm-p2p-geojson/node_modules/tape/lib/test.js:93:10)
    at Test.bound [as run] (/home/travis/build/arky/osm-p2p-geojson/node_modules/tape/lib/test.js:77:32)
    at Immediate.next [as _onImmediate] (/home/travis/build/arky/osm-p2p-geojson/node_modules/tape/lib/results.js:81:19)
    at runCallback (timers.js:810:20)
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Test failed.  See above for more details.
[0mtravis_time:end:111d8dee:start=1564216357385137763,finish=1564216357864956145,duration=479818382
[0K[31;1mThe command "npm test" exited with 1.[0m
`

**Comment by noffle** [comment]
Fixed in 4.0.3.

**Comment by arky** [comment]
Thanks @noffle !
